### ISSUE TITLE
404 Pages

### ISSUE THREAD

**Issue by Volker-Weissmann** [rust-qt/ritual#105]
Hello,
I'm trying to get a basic example to work, but sadly, some links are 404:

[Here](https://rust-qt.github.io/processing_cpp_library/running_generator/) you link to [this](https://rust-qt.github.io/processing_cpp_library/running_generator/src/main.rs).

[Here](https://docs.rs/ritual/0.0.0/ritual/) you link to [this](https://github.com/rust-qt/cpp_to_rust/tree/master/cpp_to_rust/cpp_to_rust_generator).

[Here](https://rust-qt.github.io/processing_cpp_library/setting_up/) you link to [this](https://github.com/rust-qt/ritual/blob/master/docker.builder.dockerfile)

All three links are 404.

**Comment by nawordar** [comment]
I think that the first link is supposed to point at https://github.com/rust-qt/generator-example/blob/master/src/main.rs and the third one at https://github.com/rust-qt/ritual/blob/master/scripts/docker/builder.dockerfile. I don't know about the second one.

**Comment by Riateche** [comment]
Thank you. I've fixed the links on the web site. The link on docs.rs is out of date because we no longer publish the `ritual` crate. Only crates required for building the final crates are published on crates.io.
