### ISSUE TITLE
crate syn removed export as never been part of the public API

### ISSUE THREAD

**Issue by davidedelpapa** [rust-qt/ritual#107]
`qt_macro` references `syn::export` that [has been removed](https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7) as [never been part of the public API](https://github.com/dtolnay/syn/issues/953)

Compilation of `qt_macros` fails due to the issue.

There are two places where it is called:

- [q_init_resource.rs, line 3](https://github.com/rust-qt/ritual/blob/880490edae89e7e0e5e4ec87c49fe76586513592/qt_macros/src/q_init_resource.rs#L3), and used in [line 19](https://github.com/rust-qt/ritual/blob/880490edae89e7e0e5e4ec87c49fe76586513592/qt_macros/src/q_init_resource.rs#L19)
- [slot.rs, line 3](https://github.com/rust-qt/ritual/blob/880490edae89e7e0e5e4ec87c49fe76586513592/qt_macros/src/slot.rs#L3) and used in [line 11](https://github.com/rust-qt/ritual/blob/880490edae89e7e0e5e4ec87c49fe76586513592/qt_macros/src/slot.rs#L11) and [line 15](https://github.com/rust-qt/ritual/blob/880490edae89e7e0e5e4ec87c49fe76586513592/qt_macros/src/slot.rs#L15)

In both cases, it should be possible to use [proc_macro::Span](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html) instead of passing from `export`; however it is a **nightly only feature**.
Alternatively, there is the `Span` from [proc_macro2 crate](https://docs.rs/proc-macro2/1.0.24/proc_macro2/struct.Span.html) that offer the same functionalities outside of procedural macros (slot.rs should benefit?)

**Comment by LoveIsGrief** [comment]
While we're waiting for this to get merged, the functioning `syn` version is `1.0.17`, but is there a way to force its use?

https://github.com/rust-qt/ritual/blob/880490edae89e7e0e5e4ec87c49fe76586513592/qt_macros/Cargo.toml#L14 only requires v1.0 so the patch version shouldn't matter.
