### ISSUE TITLE
Is there some way to let IDE (Clion) pop up autocomplete menu?

### ISSUE THREAD

**Issue by zjsxwc** [rust-qt/ritual#110]
My IDE Clion cannot  pop up any autocomplete menu, and I cannot jump to the qt definitions,
Is there some way to let IDE (Clion) to pop up autocomplete menu? 
Like some fake stub *.rs files used to make IDE more smart.

**Comment by zjsxwc** [comment]
it seems the generated lib.rs file size is too large.
so the IDE ignored the lib.rs code.
![QQ图片20210301134759](https://user-images.githubusercontent.com/3849577/109456883-b415ad00-7a94-11eb-9431-374455144b7a.png)

**Comment by Riateche** [comment]
Yes, you can follow the instructions [here](https://www.jetbrains.com/help/clion/configuring-file-size-limit.html) to increase the limit.

**Comment by zjsxwc** [comment]
I configure `Help|Edit custom properties`
```
idea.max.intellisense.filesize=250000000
idea.max.content.load.filesize=250000000
```,
And in `Registry` i set `cidr.max.intellisense.file.length` to 5000000000.

Now my IDE works!
