### ISSUE TITLE
Speed up add_inherited_methods

### ISSUE THREAD

**Issue by Riateche** [rust-qt/ritual#12]
`add_inherited_methods` and `inherited_methods_from` take a lot of time.

**Comment by emoon** [comment]
I could try to take a look at that code and see if it's possible to optimize it.

**Comment by Riateche** [comment]
Some tests for this function would also be nice. There are so many complicated cases. I've fixed a lot of corner cases. But a new bug came up today, see [here](https://github.com/rust-qt/cpp_to_rust/issues/22).

**Comment by Riateche** [comment]
Mostly unrelevant now.
