### ISSUE TITLE
Implement creating custom Qt signals from Rust

### ISSUE THREAD

**Issue by Riateche** [rust-qt/ritual#43]
(part of #7)

**Comment by jlgerber** [comment]
Just wondering if this is already in the works or something you have yet to figure out. This seems like the last hurdle to doing meaningful work in this library. 

Just having generic signal objects that have the same types as the current slots would be amazing.

**Comment by Riateche** [comment]
Custom signals are now implemented.

**Comment by vdods** [comment]
@Riateche Could you link to documentation on how to define signals and slots that take arguments of one's own custom Rust types?  I've been searching around for how to do this (I've looked at qt_core::Signal and the qmetaobject-rs crate but haven't managed to get anything to work).  Thank you.
