### ISSUE TITLE
Simple example of how to integrate a basic C++ library?

### ISSUE THREAD

**Issue by vlovich** [rust-qt/ritual#69]
I can't seem to find any documentation or example on how to integrate cpp_to_rust for my own C++ library.  Would it be possible to provide a simple "hello world" example?

**Comment by Riateche** [comment]
The [full_run](https://github.com/rust-qt/cpp_to_rust/blob/07e5df3655b156cddaa36a664413dcbe54b9121f/cpp_to_rust/cpp_to_rust_generator/src/tests/full_run.rs) test contains code required to process a basic C++ library. We definitely need a detailed example, but I'd rather do it after the current big changes are completed.

**Comment by vlovich** [comment]
Yeah, full_run has some stuff, but looking at the Qt generator, it looks to be very incomplete, at least as far as doing it for C++ libraries that use Qt themselves (e.g. Qt 3d view needs inheritance to catch the GL events).  I kind of got it working, but even still I have very little confidence about whether or not I wrote it correctly.

**Comment by Riateche** [comment]
An example of integrating a basic library is now available [here](https://github.com/rust-qt/generator-example).
