### ISSUE TITLE
Is there any example showing a simple UI?

### ISSUE THREAD

**Issue by Schizo** [rust-qt/ritual#78]
I'm developing **UI's** using Qt for a while and was wondering about the state of this project, which seem's promising, however I didn't see a simple GUI example and I'm not so sure as well where to start If I wanted to do one.

**Comment by Riateche** [comment]
For now, you can find an UI example at https://github.com/rust-qt/ritual/blob/master/qt_generator/qt_generator/crate_templates/widgets/examples/form1.rs.

We're currently working on the second public alpha release that will introduce some new features and API improvements. We will prepare more UI examples with the release.

**Comment by jimbo1qaz** [comment]
It seems the examples have been moved to https://github.com/rust-qt/examples/tree/master/src/bin .

**Comment by Riateche** [comment]
That's right, examples are now available in the [examples](https://github.com/rust-qt/examples) repo.
