### ISSUE TITLE
Qt Chart Support

### ISSUE THREAD

**Issue by igor-petruk** [rust-qt/ritual#84]
Please provide a crate with https://doc.qt.io/qt-5/qchart.html support. Thanks!

**Comment by Riateche** [comment]
I've [added](https://github.com/rust-qt/ritual/commit/1ce9863e9bb0dc390ef68b8888920b7cbfb9e579) `qt_charts` support. It will be included in the next release.

**Comment by Riateche** [comment]
The `qt_charts 0.3.0` crate is out. See a basic example of usage [here](https://github.com/rust-qt/examples/blob/master/src/bin/chart.rs).
