### ISSUE TITLE
help - QListOfQStandardItems - not clear how to append a QStandardItem

### ISSUE THREAD

**Issue by jlgerber** [rust-qt/ritual#97]
The append signature of QListOfQStandardItem takes ref to another QListOfQStandardItem.  I dont see how you can append an actual QStandardItem to the list.

**Comment by Riateche** [comment]
Some methods are missing on this type. I will investigate it. Thanks for the report!

**Comment by jlgerber** [comment]
Fortunately, there was another way to do what i was trying to do.

**Comment by Riateche** [comment]
Fixed in `qt_gui 0.5.0-alpha.1`. Also all similar methods across all Qt crates are fixed. The argument type in the Rust functions can be improved, though.
